name: ServerClustersBukkit
main: de.themoep.serverclusters.bukkit.ServerClustersBukkit
version: 0.2.6.3
description: Bukkit part of of the ServerClusters plugin
authors: [Phoenix616]
commands:
   tpa:
      aliases: [ctpa,call]
      description: Request a teleport to another player
      usage: /<command> <playername>
      permission: serverclusters.command.ctpa
      permission-message: You don't have the permission <permission>
   tpahere:
      aliases: [ctpahere]
      description: Request another player to teleport to you
      usage: /<command> <playername>
      permission: serverclusters.command.ctpahere
      permission-message: You don't have the permission <permission>
   tpaccept:
      aliases: [ctpaccept,tpyes]
      description: Accepts a teleport request by another player
      usage: /<command> [<playername>]
      permission: serverclusters.command.ctpaccept
      permission-message: You don't have the permission <permission>
   tpdeny:
      aliases: [ctpdeny,tpno]
      description: Denies a teleport request by another player
      usage: /<command> [<playername>]
      permission: serverclusters.command.ctpdeny
      permission-message: You don't have the permission <permission>
permissions:
   serverclusters.command.tpa:
      default: op
   serverclusters.command.tpa.intercluster:
      default: op
   serverclusters.command.tpahere:
      default: op
   serverclusters.command.tpahere.intercluster:
      default: op
   serverclusters.command.tpaccept:
      default: op
   serverclusters.command.tpdeny:
      default: op