name: ServerClustersBukkit
main: de.themoep.serverclusters.bukkit.ServerClustersBukkit
version: ${minecraft.plugin.version}
description: Bukkit part of of the ServerClusters plugin
authors: [Phoenix616]
commands:
   tpa:
      aliases: [ctpa,call]
      description: Request a teleport to another player
      usage: /<command> <playername>
      permission: serverclusters.command.tpa
      permission-message: You don't have the permission <permission>
   tpahere:
      aliases: [ctpahere]
      description: Request another player to teleport to you
      usage: /<command> <playername>
      permission: serverclusters.command.tpahere
      permission-message: You don't have the permission <permission>
   tpaccept:
      aliases: [ctpaccept,tpyes]
      description: Accepts a teleport request by another player
      usage: /<command> [<playername>]
      permission: serverclusters.command.tpaccept
      permission-message: You don't have the permission <permission>
   tpdeny:
      aliases: [ctpdeny,tpno]
      description: Denies a teleport request by another player
      usage: /<command> [<playername>]
      permission: serverclusters.command.tpdeny
      permission-message: You don't have the permission <permission>
   tpaconfirm:
      aliases: [ctpaconfirm]
      description: Confirms a previous teleport action
      usage: /<command>
      permission: serverclusters.command.tpaconfirm
      permission-message: You don't have the permission <permission>
   warp:
      aliases: [cwarp,warps]
      description: Teleports to and displays warps
      usage: /<command> [<playername>]
      permission: serverclusters.command.warp
      permission-message: You don't have the permission <permission>
   setwarp:
      aliases: [csetwarp]
      description: Set cluster warp
      usage: /<command> [<playername>]
      permission: serverclusters.command.setwarp
      permission-message: You don't have the permission <permission>
   setglobalwarp:
      aliases: [csetglobalwarp]
      description: Set global warp
      usage: /<command> [<playername>]
      permission: serverclusters.command.setglobalwarp
      permission-message: You don't have the permission <permission>
permissions:
   serverclusters.command.tpa:
      default: op
   serverclusters.command.tpahere:
      default: op
   serverclusters.command.tpaccept:
      default: op
   serverclusters.command.tpdeny:
      default: op
   serverclusters.command.tpaconfirm:
      default: op
   serverclusters.command.warp:
      default: op
   serverclusters.command.setwarp:
      default: op
   serverclusters.command.setglobalwarp:
      default: op