# backend to safe runtime data (for example loggoutservers)
# possible options: YAML or MYSQL
backend: YAML
# whether or not to wait a tick after the proxy was enabled to override any other duplicate commands
latebindCommands: true
# mysql connection information
mysql:
  user: username
  password: password1
  dbname: mydatabase
  host: localhost
  port: 3306
  tableprefix: serverclusters_
teleportDelay: 5
commandCooldown: 10
teleportTimeout: 30
queueTimeout: 30
hideVanished: false
cluster:
  Freebuild:
    server:
      - minebench
    alias: [fb, f, minebench, mb, m, survival]
  Lobby:
    server:
      - lobby
    alias:
      - l
  Test:
    server:
      - test
    alias:
      - t
  Skyblock:
    server:
      - sky
    alias:
      - sky
      - s
  Build:
    server:
      - build
    alias:
      - b
  PVP:
    server:
      - pvp
    alias:
      - p


